---
title: "The Fesshole Data Analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my data analysis website of the dataset The Fesshole.

**VERY IMPORTANT** 
**As a warning, this dataset is made of expressions that may affect the sensibility of some
since it contains profanity, words of sexual nature, and description of acts that may prove offensive.  
Use and navigate at your own discretion**

The Fesshole is a dataset in a google spreadsheet that collects the confessions
sent by anonimous people that have access to an freely accessible only form called
The Fesshole.  The form itself is available in a Twitter account of the same name
managed by 

 * The spreadsheet with all entries [can be found here.](https://docs.google.com/spreadsheets/d/1wiUl3SiU6qlRU50WN1sKZ0ERXXj_7WVvF5QFxTMTAaY/edit#gid=1599891978)
 * The public form [can be found here.](https://docs.google.com/forms/d/e/1FAIpQLSc5XIfmezx_-fDnwpKC9QW_cC3MtrHTyVTOpPiWAIOlIu6RtA/viewformd)
 * The twitter account with [all the confessions is here.](https://twitter.com/fesshole)
 * [This is the account](https://twitter.com/robmanuel) of the administrator / moderator of The Fesshole.
 
 **Content**
 
 01. [Introduction](01_introduction.html)
 02. [The Fesshole Spreadsheet](02_spreadsheet.html) 
 03. Exploratory Data Analysis
 04. Sentiment Analysis
 05. Sentiment Predictive Model
 
 
